schedule: "0 1 * * *"
concurrencyPolicy: "Forbid"
image:
  # [required] repository where meteor Docker image is available
  repository: raystack/meteor
  tag: "0.8.0"
  pullPolicy: IfNotPresent
labels: { "application": "meteor" }

config: {}
secretConfig: {}
# pass in secret names to be mounted to cronjob
ssl_secrets: []
# sample recipe usage
# recipes:
#   sample-recipe.yaml: |-
#     name: sample-recipe
#     source:
#       type: sample
#       config:
#         foo: "bar"
#     sinks:
#       - name: console
